# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c86e3a3b6f0ed55eded60c703ddd777f4e0ee67ef032157e80091fc8f467474563a20e54c52de10b091c34c380743a79394b7f90900aff3598ee68e152f648bf

test:
  secret_key_base: 850b087252fcb066ee87b2ceae643329d0ccd6b5b6618ab3dd73c4edec55a354052ce10cd6c1b6c97b71cc531bb00deaf5a18809c2c8dd53cc48e30b7b50912d

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

preproduction:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
